### ISSUE TITLE
Travis secure key

### ISSUE THREAD

**Issue by tenhobi** [josefdolezal/fit-cvut#1]
Nevím na co se to konkrétně používá a jestli to vadí (ale je to pod deploy, takže asi jo), ale obecně, nebylo by vhodné dát "secure key" (jak je to zváno) pryč z repozitáře (tj. aby to nikdo neviděl) a namísto toho to dát jako "Environment Variables" do travisu (což by mělo sloužit tuším právě na tyto účely) a odkazovat na něj proměnnou? :-)

Konkrétně toto https://github.com/josefdolezal/fit-cvut/blob/master/.travis.yml#L14

**Comment by josefdolezal** [comment]
Ahoj, v první řadě, tohle je první issue, díky za něj.

Token, který se používá k deployi je šifrovaný pomocí RSA párem privátní-veřejný klíč. Veřejný klíč je uložený u mě, tím šifruji. Privátní klíč je na Travisu a tím pádem dokáží ten token dešifrovat jen oni.

Když nastavuješ deploy na GitHub pomocí

$ travis setup releases

Zažádáš o vytvoření nového tokenu, ten zašifruješ a uložíš do souboru (děje se to samozřejmě automaticky).

V momentě kdy se bude dít deploy (git tag), Travis vezme hodnotu pole api_key, uvidí že je secure a tim pádem teprve dešifruje. To co mu vypadne z dešifrování následně použije jako token pro ověření oproti GitHub API.

Svým způsobem, to co vidíš v poli secure je to samé jako kdybys odposlechl komunikaci přes HTTPS. Vím na jaký problém poukazuješ, ale jsem přesvědčený, že takto je to ok.

Rozdíl bude vidět, když zkusíš

$ travis init
$ travis setup releases

Když v kroku "Secure API key?" dáš jednou "yes" a jednou "no", mělo by se to projevit v .travis.yml souboru.

To co jsem popsal je s odkazem na tuhle část dokumentace: https://docs.travis-ci.com/user/encryption-keys/ .
Pokud jsem to špatně pochopil nebo se pletu, dej vědět a mrknu na to podrobně.

Sorry za omezený formátování, píšu z telefonu.

**Comment by tenhobi** [comment]
OK. Já právě viděl řešení, kdy tam byla nějaká proměnná typu `$MUJ_KLIC` a ten nastavený v CI, ale nejsem si jistý, jestli to byl Travis CI nebo spíše GitLab CI, kde to mohou mít zase jinou flow. :-)

Já píšu jen pro jistotu – přeci jen lepší psát zbytečně, než si nechat něco zničit pak. :-)

**Comment by josefdolezal** [comment]
A bylo to pro deploy? Já to v jiných repozitářích používám taky, ale třeba když se připojuju na služby, které neumí travis zprostředkovat..

**Comment by tenhobi** [comment]
To netuším. No, každopádně, pokud to je tedy safe řešení, tak pohoda a zavírám. :-)
